---
title: "Performance"
author: "Michael Sumner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Manifoldr Performance}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,eval=FALSE}
f <- file.path(dp, "Data\\World\\Low Resolution\\Continents and Oceans lowres.map")
library(manifoldr)
library(rbenchmark)
benchmark(readmfd =  manifoldr:::readmfd(f, "Drawing"), 
          spatial = manifoldr:::readmfd(f, "Drawing"),
          sf = manifoldr::Drawing(f, "Drawing"), replications = 4)

a <- profr(manifoldr:::readmfd(f, "Drawing"))
```


```{r,eval=FALSE}
system.time(tab <- Drawing("C:/data/cadastre/list_parcels_hobart.map"))
#   user  system elapsed 
#   7.59    1.03    8.76 
system.time(x <- rgdal::readOGR("C:/data/cadastre/shp", "list_parcels_hobart"))
#OGR data source with driver: ESRI Shapefile 
#Source: "C:/data/cadastre/shp", layer: "list_parcels_hobart"
#with 33611 features
#It has 19 fields
#Integer64 fields read as strings:  CID PID POT_PID 
#   user  system elapsed 
#  19.22    3.13   22.95 
system.time(x <- rgdal::readOGR("C:/data/cadastre/tab", "list_parcels_hobart"))
#OGR data source with driver: MapInfo File 
#Source: "C:/data/cadastre/tab", layer: "list_parcels_hobart"
#with 33611 features
#It has 19 fields
#   user  system elapsed 
#  17.57    7.47   25.40 
```





# Timings
```{r,eval=FALSE}
f <- file.path(dp, "Data\\World\\Medium Resolution\\World Provinces.map")
system.time(x <- manifoldr:::readmfd(f, "Provinces"))
  #  user  system elapsed 
  # 23.02    0.66   24.24 
  # 
system.time(x <- manifoldr:::readmfd(f, "Provinces", spatial = TRUE))
 Error in if (byteOrder == as.raw(1L)) { : argument is of length zero 
   
```
```{r,eval=FALSE}
## Built:                R 3.2.3; ; 2016-01-17 14:03:26 UTC; windows
f <- "..Data\\World\\High Resolution\\Countries hires.map"
system.time(x <- manifoldr:::readmfd(f, "Countries"))
#  user  system elapsed 
# 100.39    1.70  103.21
format(object.size(x), unit = "Mb")
#[1] "75.5 Mb"
`